### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by scwheele** [CircleCI-Public/Salesforce-sfdx-cli-orb#6]
**Is your feature request related to a problem? Please describe.**
Windows Support

**Describe the solution you'd like**
The `auth` and `install` commands should be available from a Windows executor.

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by rcoringrato-sfdc** [comment]
When I attempt to use the `auth` command from a Windows executor the steps in the command are interpreted using Powershell. If the steps in the command were to specify bash as the shell would that allow the command to run in Windows?

**Comment by gmemstr** [comment]
@rcoringrato-sfdc Theoretically, yes, although I haven't tested this myself. It _should_ be as simple as specifying the shell at a job level. https://circleci.com/docs/2.0/configuration-reference/#lessjobnamegreater Supporting Windows in orbs is a bit tricky because there's no easy to way to switch to PowerShell if we are running in Windows (or even detect if we're in Windows in the first place).
